platform: x64

os: Visual Studio 2015

build_script:
- npm install vult -g
- mkdir build
- cd build
- call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
- cmake ../ -G "NMake Makefiles"
- nmake